### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by panama69**
tweaked the Readme

### CODE REVIEW

**Review by jhrabi — COMMENTED** [review]
Is there a reason we are encouraging people to do git clones manually instead of using a proper IDE?

**Comment by panama69** [comment]
I wanted generic instructions that anyone can use since this is publicly facing.  I did not want to get in to having to have instructions per IDE or have to update if the IDE changes.

**Comment by jhrabi** [comment]
People don't typically explain having to stand up an IDE for any project in GitHub, unless there's very special instructions on setting up the project. It's assumed at some point that if you're using GitHub, you're experienced enough to stand up an IDE. I just don't think there's a ton of value in telling people to do a checkout via git from a CLI, when they should be doing this through an IDE. Just my 2c

**Review by jhrabi — APPROVED** [review]

**Comment by panama69** [comment]
Yep, totally agree but I wanted to have something there for our presales base.  The process really would be to have them fork the project make their changes, etc. but I didn't want to confuse them too much.  As you said, anyone who uses Github will already know what to do.

**Pull request merged**
